export const colours = [
  {
    hex: '#CD5C5C',
    name: 'INDIANRED',
    rgb: 'RGB(205, 92, 92)',
    families: ['red', 'brown'],
  },
  {
    hex: '#F08080',
    name: 'LIGHTCORAL',
    rgb: 'RGB(240, 128, 128)',
    families: ['red', 'pink', 'coral', 'light'],
  },
  {
    name: 'SALMON',
    hex: '#FA8072',
    rgb: 'RGB(250, 128, 114)',
    families: ['red', 'pink', 'orange', 'salmon'],
  },
  {
    hex: '#E9967A',
    name: 'DARKSALMON',
    rgb: 'RGB(233, 150, 122)',
    families: ['red', 'pink', 'orange', 'salmon', 'dark'],
  },
  {
    hex: '#FFA07A',
    name: 'LIGHTSALMON',
    rgb: 'RGB(255, 160, 122)',
    families: ['red', 'pink', 'orange', 'salmon', 'light'],
  },
  {
    hex: '#DC143C',
    name: 'CRIMSON',
    families: ['red'],
    rgb: 'RGB(220, 20, 60)',
  },
  {
    name: 'RED',
    hex: '#FF0000',
    families: ['red'],
    rgb: 'RGB(255, 0, 0)',
  },
  // {
  //   hex: '#8B0000',
  //   name: 'DARKRED',
  //   rgb: 'RGB(139, 0, 0)',
  //   families: ['red', 'dark'],
  // },
  {
    name: 'PINK',
    hex: '#FFC0CB',
    families: ['pink'],
    rgb: 'RGB(255, 192, 203)',
  },
  {
    hex: '#FFB6C1',
    name: 'LIGHTPINK',
    rgb: 'RGB(255, 182, 193)',
    families: ['pink', 'light'],
  },
  {
    hex: '#FF69B4',
    name: 'HOTPINK',
    rgb: 'RGB(255, 105, 180)',
    families: ['pink', 'hot'],
  },
  {
    hex: '#FF1493',
    name: 'DEEPPINK',
    rgb: 'RGB(255, 20, 147)',
    families: ['pink', 'deep'],
  },
  // {
  //   hex: '#C71585',
  //   name: 'MEDIUMVIOLETRED',
  //   rgb: 'RGB(199, 21, 133)',
  //   families: ['pink', 'purple', 'violet', 'medium'],
  // },
  {
    hex: '#DB7093',
    name: 'PALEVIOLETRED',
    rgb: 'RGB(219, 112, 147)',
    families: ['pink', 'pale', 'violet'],
  },
  {
    name: 'CORAL',
    hex: '#FF7F50',
    rgb: 'RGB(255, 127, 80)',
    families: ['orange', 'coral'],
  },
  {
    name: 'TOMATO',
    hex: '#FF6347',
    rgb: 'RGB(255, 99, 71',
    families: ['orange', 'red'],
  },
  {
    hex: '#FF4500',
    name: 'ORANGERED',
    rgb: 'RGB(255, 69, 0)',
    families: ['orange', 'red'],
  },
  {
    hex: '#FF8C00',
    name: 'DARKORANGE',
    rgb: 'RGB(255, 140, 0)',
    families: ['orange', 'dark'],
  },
  {
    name: 'ORANGE',
    hex: '#FFA500',
    families: ['orange'],
    rgb: 'RGB(255, 165, 0)',
  },
  {
    name: 'GOLD',
    hex: '#FFD700',
    families: ['yellow'],
    rgb: 'RGB(255, 215, 0)',
  },
  {
    name: 'YELLOW',
    hex: '#FFFF00',
    families: ['yellow'],
    rgb: 'RGB(255, 255, 0)',
  },
  {
    hex: '#FFFFE0',
    name: 'LIGHTYELLOW',
    rgb: 'RGB(255, 255, 224)',
    families: ['yellow', 'light'],
  },
  {
    hex: '#FFFACD',
    name: 'LEMONCHIFFON',
    rgb: 'RGB(255, 250, 205)',
    families: ['yellow', 'lemon'],
  },
  {
    hex: '#FAFAD2',
    rgb: 'RGB(250, 250, 210)',
    name: 'LIGHTGOLDENRODYELLOW',
    families: ['yellow', 'light', 'goldenrod', 'tan'],
  },
  {
    hex: '#FFEFD5',
    name: 'PAPAYAWHIP',
    rgb: 'RGB(255, 239, 213)',
    families: ['pink', 'tan'],
  },
  {
    hex: '#FFE4B5',
    name: 'MOCCASIN',
    rgb: 'RGB(255, 228, 181)',
    families: ['pink', 'tan'],
  },
  {
    hex: '#FFDAB9',
    name: 'PEACHPUFF',
    rgb: 'RGB(255, 218, 185)',
    families: ['pink', 'orange', 'peach'],
  },
  {
    hex: '#EEE8AA',
    name: 'PALEGOLDENROD',
    rgb: 'RGB(238, 232, 170)',
    families: ['yellow', 'tan', 'pale', 'goldenrod'],
  },
  {
    name: 'KHAKI',
    hex: '#F0E68C',
    rgb: 'RGB(240, 230, 140)',
    families: ['yellow', 'tan', 'khaki'],
  },
  {
    hex: '#BDB76B',
    name: 'DARKKHAKI',
    rgb: 'RGB(189, 183, 107)',
    families: ['yellow', 'tan', 'khaki', 'dark'],
  },
  {
    hex: '#E6E6FA',
    name: 'LAVENDER',
    families: ['purple'],
    rgb: 'RGB(230, 230, 250)',
  },
  {
    hex: '#D8BFD8',
    name: 'THISTLE',
    families: ['purple'],
    rgb: 'RGB(216, 191, 216)',
  },
  {
    name: 'PLUM',
    hex: '#DDA0DD',
    families: ['purple'],
    rgb: 'RGB(221, 160, 221)',
  },
  {
    name: 'VIOLET',
    hex: '#EE82EE',
    rgb: 'RGB(238, 130, 238)',
    families: ['purple', 'violet', 'pink'],
  },
  {
    name: 'ORCHID',
    hex: '#DA70D6',
    rgb: 'RGB(218, 112, 214)',
    families: ['purple', 'orchid'],
  },
  {
    hex: '#FF00FF',
    name: 'FUCHSIA',
    rgb: 'RGB(255, 0, 255)',
    families: ['purple', 'pink'],
  },
  {
    hex: '#FF00FF',
    name: 'MAGENTA',
    rgb: 'RGB(255, 0, 255)',
    families: ['purple', 'pink', 'magenta'],
  },
  {
    hex: '#BA55D3',
    name: 'MEDIUMORCHID',
    rgb: 'RGB(186, 85, 211)',
    families: ['purple', 'orchid', 'medium'],
  },
  {
    hex: '#9370DB',
    name: 'MEDIUMPURPLE',
    rgb: 'RGB(147, 112, 219)',
    families: ['purple', 'medium'],
  },
  // {
  //   hex: '#663399',
  //   name: 'REBECCAPURPLE',
  //   rgb: 'RGB(102, 51, 153)',
  //   families: ['purple', 'blue'],
  // },
  // {
  //   hex: '#8A2BE2',
  //   name: 'BLUEVIOLET',
  //   rgb: 'RGB(138, 43, 226)',
  //   families: ['purple', 'blue', 'violet'],
  // },
  // {
  //   hex: '#9400D3',
  //   name: 'DARKVIOLET',
  //   rgb: 'RGB(148, 0, 211)',
  //   families: ['purple', 'dark', 'violet'],
  // },
  // {
  //   hex: '#9932CC',
  //   name: 'DARKORCHID',
  //   rgb: 'RGB(153, 50, 204)',
  //   families: ['purple', 'dark', 'orchid'],
  // },
  // {
  //   hex: '#8B008B',
  //   name: 'DARKMAGENTA',
  //   rgb: 'RGB(139, 0, 139)',
  //   families: ['purple', 'dark', 'magenta'],
  // },
  // {
  //   name: 'PURPLE',
  //   hex: '#800080',
  //   families: ['purple'],
  //   rgb: 'RGB(128, 0, 128)',
  // },
  // {
  //   name: 'INDIGO',
  //   hex: '#4B0082',
  //   rgb: 'RGB(75, 0, 130)',
  //   families: ['purple', 'blue'],
  // },
  {
    hex: '#6A5ACD',
    name: 'SLATEBLUE',
    rgb: 'RGB(106, 90, 205)',
    families: ['purple', 'blue', 'slate'],
  },
  // {
  //   hex: '#483D8B',
  //   name: 'DARKSLATEBLUE',
  //   rgb: 'RGB(72, 61, 139)',
  //   families: ['purple', 'blue', 'slate', 'dark'],
  // },
  {
    hex: '#7B68EE',
    name: 'MEDIUMSLATEBLUE',
    rgb: 'RGB(123, 104, 238)',
    families: ['purple', 'blue', 'slate', 'medium'],
  },
  {
    hex: '#ADFF2F',
    name: 'GREENYELLOW',
    rgb: 'RGB(173, 255, 47)',
    families: ['green', 'yellow'],
  },
  {
    hex: '#7FFF00',
    name: 'CHARTREUSE',
    families: ['green'],
    rgb: 'RGB(127, 255, 0)',
  },
  {
    hex: '#7CFC00',
    name: 'LAWNGREEN',
    families: ['green'],
    rgb: 'RGB(124, 252, 0)',
  },
  {
    name: 'LIME',
    hex: '#00FF00',
    families: ['green'],
    rgb: 'RGB(0, 255, 0)',
  },
  {
    hex: '#32CD32',
    name: 'LIMEGREEN',
    families: ['green'],
    rgb: 'RGB(50, 205, 50)',
  },
  {
    hex: '#98FB98',
    name: 'PALEGREEN',
    rgb: 'RGB(152, 251, 152)',
    families: ['green', 'pale'],
  },
  {
    hex: '#90EE90',
    name: 'LIGHTGREEN',
    rgb: 'RGB(144, 238, 144)',
    families: ['green', 'light'],
  },
  {
    hex: '#00FA9A',
    rgb: 'RGB(0, 250, 154)',
    name: 'MEDIUMSPRINGGREEN',
    families: ['green', 'medium', 'spring'],
  },
  {
    hex: '#00FF7F',
    name: 'SPRINGGREEN',
    rgb: 'RGB(0, 255, 127)',
    families: ['green', 'spring'],
  },
  {
    hex: '#3CB371',
    name: 'MEDIUMSEAGREEN',
    rgb: 'RGB(60, 179, 113)',
    families: ['green', 'sea', 'medium'],
  },
  {
    hex: '#2E8B57',
    name: 'SEAGREEN',
    rgb: 'RGB(46, 139, 87)',
    families: ['green', 'sea'],
  },
  {
    hex: '#228B22',
    name: 'FORESTGREEN',
    rgb: 'RGB(34, 139, 34)',
    families: ['green', 'forest'],
  },
  // {
  //   name: 'GREEN',
  //   hex: '#008000',
  //   families: ['green'],
  //   rgb: 'RGB(0, 128, 0)',
  // },
  // {
  //   hex: '#006400',
  //   name: 'DARKGREEN',
  //   rgb: 'RGB(0, 100, 0)',
  //   families: ['green', 'dark'],
  // },
  {
    hex: '#9ACD32',
    name: 'YELLOWGREEN',
    rgb: 'RGB(154, 205, 50)',
    families: ['green', 'yellow'],
  },
  // {
  //   hex: '#6B8E23',
  //   name: 'OLIVEDRAB',
  //   rgb: 'RGB(107, 142, 35)',
  //   families: ['green', 'olive'],
  // },
  {
    name: 'OLIVE',
    hex: '#6B8E23',
    rgb: 'RGB(128, 128, 0)',
    families: ['green', 'olive'],
  },
  // {
  //   hex: '#556B2F',
  //   name: 'DARKOLIVEGREEN',
  //   rgb: 'RGB(85, 107, 47)',
  //   families: ['green', 'olive', 'dark'],
  // },
  {
    hex: '#66CDAA',
    name: 'MEDIUMAQUAMARINE',
    rgb: 'RGB(102, 205, 170)',
    families: ['green', 'blue', 'aquamarine', 'medium'],
  },
  {
    hex: '#8FBC8B',
    name: 'DARKSEAGREEN',
    rgb: 'RGB(143, 188, 139)',
    families: ['green', 'sea', 'dark'],
  },
  {
    hex: '#20B2AA',
    name: 'LIGHTSEAGREEN',
    rgb: 'RGB(32, 178, 170)',
    families: ['green', 'blue', 'sea', 'light'],
  },
  // {
  //   hex: '#008B8B',
  //   name: 'DARKCYAN',
  //   rgb: 'RGB(0, 139, 139)',
  //   families: ['green', 'blue', 'cyan', 'dark'],
  // },
  // {
  //   name: 'TEAL',
  //   hex: '#008080',
  //   rgb: 'RGB(0, 128, 128)',
  //   families: ['green', 'blue'],
  // },
  {
    name: 'AQUA',
    hex: '#00FFFF',
    rgb: 'RGB(0, 255, 255)',
    families: ['blue', 'aqua'],
  },
  {
    name: 'CYAN',
    hex: '#00FFFF',
    rgb: 'RGB(0, 255, 255)',
    families: ['blue', 'cyan'],
  },
  {
    hex: '#E0FFFF',
    name: 'LIGHTCYAN',
    rgb: 'RGB(224, 255, 255)',
    families: ['blue', 'cyan', 'light'],
  },
  {
    hex: '#AFEEEE',
    name: 'PALETURQUOISE',
    rgb: 'RGB(175, 238, 238)',
    families: ['blue', 'turquoise', 'pale'],
  },
  {
    hex: '#7FFFD4',
    name: 'AQUAMARINE',
    rgb: 'RGB(127, 255, 212)',
    families: ['blue', 'aquamarine'],
  },
  {
    hex: '#40E0D0',
    name: 'TURQUOISE',
    rgb: 'RGB(64, 224, 208)',
    families: ['blue', 'turquoise'],
  },
  {
    hex: '#48D1CC',
    name: 'MEDIUMTURQUOISE',
    rgb: 'RGB(72, 209, 204)',
    families: ['blue', 'turquoise', 'medium'],
  },
  {
    hex: '#00CED1',
    name: 'DARKTURQUOISE',
    rgb: 'RGB(0, 206, 209)',
    families: ['blue', 'turquoise', 'dark'],
  },
  {
    hex: '#5F9EA0',
    name: 'CADETBLUE',
    rgb: 'RGB(95, 158, 160)',
    families: ['blue', 'gray'],
  },
  // {
  //   hex: '#4682B4',
  //   name: 'STEELBLUE',
  //   rgb: 'RGB(70, 130, 180)',
  //   families: ['blue', 'steel'],
  // },
  {
    hex: '#B0C4DE',
    name: 'LIGHTSTEELBLUE',
    rgb: 'RGB(176, 196, 222)',
    families: ['blue', 'steel', 'light'],
  },
  {
    hex: '#B0E0E6',
    name: 'POWDERBLUE',
    families: ['blue'],
    rgb: 'RGB(176, 224, 230)',
  },
  {
    hex: '#ADD8E6',
    name: 'LIGHTBLUE',
    rgb: 'RGB(173, 216, 230)',
    families: ['blue', 'light'],
  },
  {
    hex: '#87CEEB',
    name: 'SKYBLUE',
    rgb: 'RGB(135, 206, 235)',
    families: ['blue', 'sky'],
  },
  {
    hex: '#87CEFA',
    name: 'LIGHTSKYBLUE',
    rgb: 'RGB(135, 206, 250)',
    families: ['blue', 'sky', 'light'],
  },
  {
    hex: '#00BFFF',
    name: 'DEEPSKYBLUE',
    rgb: 'RGB(0, 191, 255)',
    families: ['blue', 'sky', 'deep'],
  },
  {
    hex: '#1E90FF',
    name: 'DODGERBLUE',
    families: ['blue'],
    rgb: 'RGB(30, 144, 255)',
  },
  {
    hex: '#6495ED',
    families: ['blue'],
    name: 'CORNFLOWERBLUE',
    rgb: 'RGB(100, 149, 237)',
  },
  {
    hex: '#4169E1',
    name: 'ROYALBLUE',
    families: ['blue'],
    rgb: 'RGB(65, 105, 225)',
  },
  // {
  //   name: 'BLUE',
  //   hex: '#0000FF',
  //   families: ['blue'],
  //   rgb: 'RGB(0, 0, 255)',
  // },
  // {
  //   hex: '#0000CD',
  //   name: 'MEDIUMBLUE',
  //   rgb: 'RGB(0, 0, 205)',
  //   families: ['blue', 'medium'],
  // },
  // {
  //   hex: '#00008B',
  //   name: 'DARKBLUE',
  //   rgb: 'RGB(0, 0, 139)',
  //   families: ['blue', 'dark'],
  // },
  // {
  //   name: 'NAVY',
  //   hex: '#00008B',
  //   rgb: 'RGB(0, 0, 128)',
  //   families: ['blue', 'dark'],
  // },
  // {
  //   hex: '#191970',
  //   name: 'MIDNIGHTBLUE',
  //   rgb: 'RGB(25, 25, 112))',
  //   families: ['blue', 'dark'],
  // },
  {
    hex: '#FFF8DC',
    name: 'CORNSILK',
    rgb: 'RGB(255, 248, 220)',
    families: ['brown', 'tan'],
  },
  {
    hex: '#FFEBCD',
    name: 'BLANCHEDALMOND',
    rgb: 'RGB(255, 235, 205)',
    families: ['brown', 'tan'],
  },
  {
    name: 'BISQUE',
    hex: '#FFE4C4',
    rgb: 'RGB(255, 228, 196)',
    families: ['brown', 'tan'],
  },
  {
    hex: '#FFDEAD',
    name: 'NAVAJOWHITE',
    rgb: 'RGB(255, 222, 173)',
    families: ['brown', 'tan'],
  },
  {
    name: 'WHEAT',
    hex: '#F5DEB3',
    rgb: 'RGB(245, 222, 179)',
    families: ['brown', 'tan'],
  },
  {
    hex: '#DEB887',
    name: 'BURLYWOOD',
    rgb: 'RGB(222, 184, 135)',
    families: ['brown', 'tan'],
  },
  {
    name: 'TAN',
    hex: '#D2B48C',
    rgb: 'RGB(210, 180, 140)',
    families: ['brown', 'tan'],
  },
  {
    hex: '#BC8F8F',
    name: 'ROSYBROWN',
    rgb: 'RGB(188, 143, 143)',
    families: ['brown', 'tan'],
  },
  {
    hex: '#F4A460',
    name: 'SANDYBROWN',
    rgb: 'RGB(244, 164, 96)',
    families: ['brown', 'orange'],
  },
  {
    hex: '#DAA520',
    name: 'GOLDENROD',
    rgb: 'RGB(218, 165, 32)',
    families: ['brown', 'goldenrod', 'orange'],
  },
  {
    hex: '#B8860B',
    name: 'DARKGOLDENROD',
    rgb: 'RGB(184, 134, 11)',
    families: ['brown', 'orange', 'goldenrod', 'dark'],
  },
  {
    name: 'PERU',
    hex: '#CD853F',
    rgb: 'RGB(205, 133, 63)',
    families: ['brown', 'orange'],
  },
  {
    hex: '#D2691E',
    name: 'CHOCOLATE',
    rgb: 'RGB(210, 105, 30)',
    families: ['brown', 'orange'],
  },
  // {
  //   hex: '#8B4513',
  //   name: 'SADDLEBROWN',
  //   families: ['brown'],
  //   rgb: 'RGB(139, 69, 19)',
  // },
  {
    name: 'SIENNA',
    hex: '#A0522D',
    families: ['brown'],
    rgb: 'RGB(160, 82, 45)',
  },
  // {
  //   name: 'BROWN',
  //   hex: '#A52A2A',
  //   rgb: 'RGB(165, 42, 42)',
  //   families: ['brown', 'red'],
  // },
  // {
  //   name: 'MAROON',
  //   hex: '#800000',
  //   rgb: 'RGB(128, 0, 0)',
  //   families: ['brown', 'red'],
  // },
  {
    name: 'WHITE',
    hex: '#FFFFFF',
    families: ['white'],
    rgb: 'RGB(255, 255, 255)',
  },
  {
    name: 'SNOW',
    hex: '#FFFAFA',
    families: ['white'],
    rgb: 'RGB(255, 250, 250)',
  },
  {
    hex: '#F0FFF0',
    name: 'HONEYDEW',
    families: ['white'],
    rgb: 'RGB(240, 255, 240)',
  },
  {
    hex: '#F5FFFA',
    name: 'MINTCREAM',
    families: ['white'],
    rgb: 'RGB(245, 255, 250)',
  },
  {
    name: 'AZURE',
    hex: '#F0FFFF',
    families: ['white'],
    rgb: 'RGB(240, 255, 255)',
  },
  {
    hex: '#F0F8FF',
    name: 'ALICEBLUE',
    families: ['white'],
    rgb: 'RGB(240, 248, 255)',
  },
  {
    hex: '#F8F8FF',
    name: 'GHOSTWHITE',
    families: ['white'],
    rgb: 'RGB(248, 248, 255)',
  },
  {
    hex: '#F5F5F5',
    name: 'WHITESMOKE',
    families: ['white'],
    rgb: 'RGB(245, 245, 245)',
  },
  {
    hex: '#FFF5EE',
    name: 'SEASHELL',
    rgb: 'RGB(255, 245, 238)',
    families: ['white', 'pink'],
  },
  {
    name: 'BEIGE',
    hex: '#F5F5DC',
    rgb: 'RGB(245, 245, 220)',
    families: ['white', 'tan'],
  },
  {
    hex: '#FDF5E6',
    name: 'OLDLACE',
    rgb: 'RGB(253, 245, 230)',
    families: ['white', 'tan'],
  },
  {
    hex: '#FDF5E6',
    name: 'FLORALWHITE',
    rgb: 'RGB(253, 245, 230)',
    families: ['white', 'tan'],
  },
  {
    name: 'IVORY',
    hex: '#FFFFF0',
    rgb: 'RGB(255, 255, 240)',
    families: ['white', 'tan'],
  },
  {
    hex: '#FAEBD7',
    name: 'ANTIQUEWHITE',
    rgb: 'RGB(250, 235, 215)',
    families: ['white', 'tan'],
  },
  {
    name: 'LINEN',
    hex: '#FAF0E6',
    rgb: 'RGB(250, 240, 230)',
    families: ['white', 'tan'],
  },
  {
    hex: '#FFF0F5',
    name: 'LAVENDERBLUSH',
    rgb: 'RGB(255, 240, 245)',
    families: ['white', 'lavender', 'pink'],
  },
  {
    hex: '#FFE4E1',
    name: 'MISTYROSE',
    rgb: 'RGB(255, 228, 225)',
    families: ['white', 'pink'],
  },
  {
    hex: '#DCDCDC',
    name: 'GAINSBORO',
    families: ['gray'],
    rgb: 'RGB(220, 220, 220)',
  },
  {
    hex: '#D3D3D3',
    name: 'LIGHTGRAY',
    rgb: 'RGB(211, 211, 211)',
    families: ['gray', 'light'],
  },
  {
    name: 'SILVER',
    hex: '#C0C0C0',
    families: ['gray'],
    rgb: 'RGB(192, 192, 192)',
  },
  {
    hex: '#A9A9A9',
    name: 'DARKGRAY',
    rgb: 'RGB(169, 169, 169)',
    families: ['gray', 'dark'],
  },
  {
    name: 'GRAY',
    hex: '#808080',
    families: ['gray'],
    rgb: 'RGB(128, 128, 128)',
  },
  // {
  //   hex: '#696969',
  //   name: 'DIMGRAY',
  //   families: ['gray'],
  //   rgb: 'RGB(105, 105, 105)',
  // },
  {
    hex: '#778899',
    name: 'LIGHTSLATEGRAY',
    rgb: 'RGB(119, 136, 153)',
    families: ['gray', 'light', 'slate'],
  },
  {
    hex: '#708090',
    name: 'SLATEGRAY',
    rgb: 'RGB(112, 128, 144)',
    families: ['gray', 'slate'],
  },
  {
    hex: '#2F4F4F',
    name: 'DARKSLATEGRAY',
    rgb: 'RGB(47, 79, 79)',
    families: ['gray', 'slate', 'dark'],
  },
  {
    name: 'BLACK',
    hex: '#000000',
    rgb: 'RGB(0, 0, 0)',
    families: ['black'],
  },
];
