export const JSDeveloperThoughts = [
  `Who’s fault was it?`,
  `Blame someone, anyone.`,
  `Oops. Not again.`,
  `I test in prod`,
  `Another day, another disaster.`,
  `Someone’s in trouble.`,
  `I’ve seen worse… maybe.`,
  `Who wrote this?`,
  `I wonder if McDonalds is hiring.`,
  `What does grass feel like?`,
  `Someone check the stock market.`,
  `Who let this function exist?`,
  `Callbacks are a war crime.`,
  `I’m a JS dev, send help.`,
  `My life is just callbacks and regrets.`,
  `My brain is a garbage collected heap.`,
  `The only constant is undefined.`,
  `undefined is my spirit animal.`,
  `My stack trace knows more about me than I do.`,
  `The only thing constant is my regret.`,
  `Who even invented modules?`,
  `I’m the main character in someone else’s bug report.`,
  `Another day, another Stack Overflow spiral.`,
  `I’m 80% caffeine, 20% regret.`,
  `Somehow I get paid for this.`,
  `Every deployment is a personal gamble.`,
  `There’s always one more framework.`,
  `Does anyone else feel like this or am I cursed.`,
  `They told me I’d ship features, not despair.`,
  `Is this what adulthood feels like?`,
  `Mamma mia, time for some spaghetti.`,
  `Sometimes I wonder if I’m the bug.`,
  `Is it too late to quit?`,
  `My mental stack overflows daily.`,
  `I ship despair in 2KB chunks.`,
  `Every bug is a personal insult.`,
  `I consider burning my laptop ritualistically.`,
  `My brain just threw a runtime error.`,
  `Whats vitamin D?`,
  `Fanculo a questi spaghetti.`,
  `Theres no honour in fixing this nightmare.`,
  `Yep, this definitely looks maintainable.`,
  `Ah yes, so this is what clean code looks like.`,
  `Oh look, another utils.js with 5,000 lines, beautiful.`,
  `Yep, everything is “modular,” except when it isn’t.`,
  `So much for single responsibility, this file is responsible for my breakdown.`,
  `This techdebt has techdebt.`,
  `Whoever wrote this should be on a watchlist.`,
  `Is spaghetti an official design pattern now?`,
  `This code smells like unpaid internships.`,
  `Clean coding principles? More like Stockholm syndrome principles.`,
  `I’ve seen ransom notes more readable than this.`,
  `This promise chain looks like a cry for help.`,
  `I should rename this file footgun.js.`,
  `Let's rewrite this in Rust.`,
  `I'm gonna pop a blood vessel.`,
  `Cry :(`,
  `Time to update my LinkedIn profile.`,
  `Strike two.`,
  `How am I going to explain the gap on my resume?`,
  `I'm hope your company covers therapy.`,
  `This must have been written by a 10x developer.`,
  `I thought Typescript was supposed to catch runtime errors.`,
];
